export const GET_ALL_CASES = 'GET_ALL_CASES';
export const GET_COUNTRYWISE_CASES = 'GET_COUNTRYWISE_CASES';
export const GET_COUNTRYWISE_CASES_SUCCESS = 'GET_COUNTRYWISE_CASES_SUCCESS';
export const GET_TOTAL_CASES = 'GET_TOTAL_CASES';
export const GET_TOTAL_CASES_SUCCESS = 'GET_TOTAL_CASES_SUCCESS';
